; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv

build_flags =
    -D DEBUG_MODE      ; ← commenta per Serial normale
    -D FIREBASE_MODE   ; ← commenta per girare senza Firebase
    -I src
    -I include
	-I src/1.core
    -I src/2.model
    -I src/3.system
    -I src/4.monitors
    -I src/5.controllers
    -I src/6.apis
; monitor_speed = 115200
; upload_protocol = esptool
; upload_port = COM3    

upload_protocol = espota
upload_port = 192.168.1.140
upload_flags = --auth=semenzaio123

lib_deps = 
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
	esp32async/AsyncTCP@^3.4.10
	esp32async/ESPAsyncWebServer@^3.10.0
	mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17
