; ============================================================
;  platformio.ini — Semenzaio ESP32 v2.0
; ============================================================

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = min_spiffs.csv

build_flags =
    -D DEBUG_MODE
    -D FIREBASE_MODE
    -I src
    -I include
    -I src/1.core
    -I src/2.model
    -I src/3.system
    -I src/4.monitors
    -I src/5.controllers
    -I src/6.api

; Upload via OTA
upload_protocol = espota
upload_port = 192.168.1.140
upload_flags = --auth=semenzaio123

; Oppure via USB (decommenta e commenta OTA sopra)
; upload_protocol = esptool
; upload_port = COM3
; monitor_speed = 115200

lib_deps = 
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^4.0.6
    esp32async/AsyncTCP@^3.4.10
    esp32async/ESPAsyncWebServer@^3.10.0
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.17
